### ISSUE TITLE
[SUGGESTION] Logs to file feature

### ISSUE THREAD

**Issue by tuxayo** [Sav22999/common-voice-android#92] opened 2020-06-13 17:29 UTC
**Description feedback/suggestion**
The logcat don't mention that it's from Common Voice (see #91). On less clean ROMs (like stock one) were the logcat can be polluted by warnings, it would make hard to find the Common Voice logs.

Many other app don't use System.out bug this: https://stackoverflow.com/questions/7959263/android-log-v-log-d-log-i-log-w-log-e-when-to-use-each-one

It seems to automatically prefix the output with the app name.
And allows to manage log levels.

**Comment by Sav22999** [comment] 2020-06-13 17:37
The "log" is not available now. That feature will arrive later

**Comment by tuxayo** [comment] 2020-06-14 15:58
Odd, the Log class has been since the first version of Android.
https://developer.android.com/reference/android/util/Log

So you should be free to use it instead of println() the next time you need to log/output something.

**Comment by Sav22999** [comment] 2020-06-14 16:06
@tuxayo yes, sure, I know. But I'll add a feature which save logs to a file, so you can attach that file when you report an issue. :)

**Comment by Sav22999** [comment] 2020-06-14 16:08
This issue is a duplicate of #41

**Closed** 2020-06-19 09:11 UTC
Labels: ✅ closed, ✚ enhancement, 🔀 duplicate
