### ISSUE TITLE
App crashes after firefox login

### ISSUE THREAD

**Issue by stop5** [Sav22999/common-voice-android#29] opened 2020-02-05 14:35 UTC
Version: 0.2.2b
Android: 8.1
Phone: BQ Aquaris Pro
Language Phone: German
Language app: i tried it with english and german.
Ram phone: 3.5 gigabyte

After i enter my account data with the totp, the app tries to show my profile and crashes. After that its also impossible to verify records, since it cant load the data.

**Comment by Sav22999** [comment] 2020-02-05 14:47
@stop5  Oh, I'm so sorry to this crash.
Could you, please, tell me more details about your phone? (Model, RAM, OS version, Language you are using for OS and for the app). Thanks

**Comment by stop5** [comment] 2020-02-05 22:00
@Sav22999 i put the data in it.

**Comment by Sav22999** [comment] 2020-02-05 22:18
Perfect, thank you. I'll look for a solution.
If you have other bugs, open a new Issue or you can also contact me via Telegram (directly form the app > Settings > Contact developer on Telegram).

**Comment by stop5** [comment] 2020-02-05 23:01
@Sav22999 i thought about it, but i think this is the best way to track this.

**Comment by Sav22999** [comment] 2020-02-05 23:09
@stop5  Yes, sure! In fact when a person contact me on Telegram, I (personally) open an Issue 😄 but anyway, you can contact me in every moment.
In addition, the problem should be solved in some steps and could be not necessary open a new issue, so telegram could be the fastest way to get support 😄

**Comment by Sav22999** [comment] 2020-02-06 14:14
@stop5 I've tried to reproduce the bug, but I can't. Could you take a video of your screen when the bug happens?
Of course hide you data, I want to see just where and what it happens. (you can send on telegram, if you prefer)

In addition, I advice you (if you have some free-minutes) to translate the app in German 😄 on [Crowdin](https://crowdin.com/project/common-voice-android)

**Comment by tleydxdy** [comment] 2020-02-13 01:43
I'm also having crash issues from the fdroid build after I login

**Comment by Sav22999** [comment] 2020-02-13 01:57
@tleydxdy Really, I'm so sorry. I can't reproduce that issue, so if you can send to me (on Telegram) a recording of it. So, I can see where it happens and analyse better. Thanks

**Comment by Sav22999** [comment] 2020-02-13 11:49
@stop5 @tleydxdy I'm adding some alerts (message dialogs), so you can tell me exactly what's the error it returns.
In addition, I want to ask to you:
- The crash is after you inserted your username/password, so after you tapped on "Login", or before?
- What happens when app crashed. System tell you "App doesn't respond"? Or the app just close itself? Thanks

**Comment by tleydxdy** [comment] 2020-02-13 16:11
the crash happens right after log in, or when opening app again and click "profile". Crash message is "Common Voice keep stopping"

**Comment by Sav22999** [comment] 2020-02-13 16:14
@tleydxdy thank you very much. This details is very important to know the issue. I'm working to find and solve this bug 👍

**Comment by Sav22999** [comment] 2020-02-13 16:27
If you have some minutes, could you try to install the 0.2.3a release (you can find the apk in the #30 pr)). So try to do the login and tell me what happens. If the app show you a message error, please send me a screenshot of it (before click on "Show details"). I think I've found the bug, but I'm want to be sure 😄

**Comment by Sav22999** [comment] 2020-02-13 16:27
@tleydxdy  If you have some minutes, could you try to install the 0.2.3a release (you can find the apk in the #30 pr)). So try to do the login and tell me what happens. If the app show you a message error, please send me a screenshot of it (before click on "Show details"). I think I've found the bug, but I'm want to be sure 😄

**Comment by tleydxdy** [comment] 2020-02-13 19:05
I think I have figured out why. Login with firefox account will not create a profile for you on common voice. Once I logged in on the web and fill in my profile that no longer crashes.

**Comment by Sav22999** [comment] 2020-02-13 19:43
@tleydxdy Oh, perfect. Thanks very much. So you logged in eith Firefox Accouts the first time directly from the app?

**Comment by tleydxdy** [comment] 2020-02-13 21:56
yep

**Comment by Sav22999** [comment] 2020-02-13 22:00
@tleydxdy Perfect. Thank you very much. I'm working to this bug and in some hours (I hope) I'll publish the fix-release.
If you want to contribute on the project, you can translate the app in your language (if it's not already translated in it).
😄

**Closed** 2020-02-14 00:32 UTC
Labels: ‼️ priority, 🆘 help wanted, 🐞 bug, 🔜 in progress

**Comment by Sav22999** [comment] 2020-02-14 00:33
@tleydxdy @stop5 I've fixed this bug, in 0.2.3b the app shouldn't crash anymore.
Really thanks to @tleydxdy 😄
