### ISSUE TITLE
[BUG] Wrong language

### ISSUE THREAD

**Issue by PanderMusubi** [Sav22999/common-voice-android#53] opened 2020-04-18 14:27 UTC
**Description bug**
Explain what to do when text and voice from another language is being shown/played. Either let the user know to use skip or thumbs down, or (perhaps better) make a button to indicate wrong language.

**Comment by Sav22999** [comment] 2020-04-18 14:29
@PanderMusubi I close this issue because it is a duplicate of #47. For now you can use "Skip" button 😄

**Closed** 2020-04-18 14:30 UTC
Labels: ✖️ closed, 🐞 bug, 🔀 duplicate
