### ISSUE TITLE
[BUG] Login fails due to privacy policy

### ISSUE THREAD

**Issue by rYR79435** [Sav22999/common-voice-android#99] opened 2020-06-24 11:01 UTC
_Android (OS) version:_ 9.0
_App release:_ 2.0 (113)
_From what store have you installed the app?:_  F-Droid
_Are there installed Google Services on your device?_ Yes

**Description bug**
After updating to 2.0 I was logged out of my account (maybe separate bug?). Upon logging in a prompt appeared asking me to accept the privacy policy on the website (related #94). I cannot find such a thing on the Common Voice website and can thus not log into the app anymore.
I have used the app before and it worked.

**Comment by Sav22999** [comment] 2020-06-24 11:37
Please, try again to log in. That bug was caused, maybe, due to the update.

**Comment by contactobscurantist** [comment] 2020-06-24 12:24
I had the same issue with version (2.0), when trying to login with Firefox Account, application suggests account present on phone, but then it propmts for e-mail confirmation - which never gets sent.
Also, during whole login process, app's data usage is zero. 

Older version 1.4.4 requires entering firefox account details manually, but allows to succesfullly login.

So i downgraded to 1.4.4, logged in, updated the app, and it has no active acount.
Choosing to login with firefox account, and pressing "another account" instead of "log in as *account name*" prompt finally got me in!
Weird, huh?

**Comment by Sav22999** [comment] 2020-06-24 12:41
@contactobscurantist that's very weird 🤔 
Could you try to upgrade to 2.0 and then clear data? (then open ad usual and try in this way)

**Comment by Sav22999** [comment] 2020-06-24 12:43
@rYR79435 also you. Please, try to clear data of the app and launch it again as usual... I think it's a cookies issue (even if "Login" section should clear them after login/logout)

**Comment by Sav22999** [comment] 2020-06-24 12:46
I advice you to use 2.0 instead of 1.4.4 (or earlier versions) because it has new features, like sending in background, a new library to download/upload, which works better, and also the "offline mode" (and of course in the new version are fixed many bugs)

**Comment by contactobscurantist** [comment] 2020-06-24 14:16
@Sav22999 
Just did that, i think i've found the problem.

So, 'Login with Firefox' process goes like this:
1. Entering email
2. Entering password
3. One-time password
4. E-mail code

At step 3 i switched to the authenticator app, copied code, and when switching back Common Voice app lost my login progress - prompting to log in using whatever method.
But after that, when choosing Firefox Account, it remembered previosly entered account - so it presented only button to login into my account. But this time, steps 1 to 3 got omitted, and only (disfunctional) e-mail code screen is present.

Entering same email through "choose different account" produces the same result, until app data is cleared.

**Comment by Sav22999** [comment] 2020-06-24 14:20
@contactobscurantist ok, yes. I don't have that problem, and I use authenticator app too.
Please, could you tell me what's your Android version? 😄
Because the app should come back to the same screen... maybe you disabled background processes? So when you switch from an app to another one, maybe, it close Common Voice Android process...

Update me please 😄

**Comment by contactobscurantist** [comment] 2020-06-24 14:30
@Sav22999 
You're right!
Indeed, looks like it was triggered by power-saving feature - 'Power-save performance profile' on Lineage OS 16.
I wonder if same problem may persist on low-memory devices?
Thank you for support!

**Comment by Sav22999** [comment] 2020-06-24 14:35
@contactobscurantist Maybe yes, but I'm not sure.
Anyway, I'm happy you solved this problem 😄 

@rYR79435 I wait your answer, in the meantime I add label "waiting" (after (about) 10 days I'll close the issue if there's no answer)

**Comment by baditaflorin** [comment] 2020-06-24 14:37
Same problem here + tested on my girlfriend phone.
Also first you should put the user to login to moziila voices and create account, and then and after that to allow user to try to login. 

Because in this workflow I will find out I need to create an account to late after I had to first login for nothing, but I because I will need to do it again after I create the profile in Mozilla. 

And try to allow the login to access the real browser, not the sandbox, because means that I have to enter user and password, instead use default browser and rely on the cookies and tokens that I already have to be able to sign

**Comment by baditaflorin** [comment] 2020-06-24 14:39
Samsung S10 Android 10

**Comment by Sav22999** [comment] 2020-06-24 14:42
@baditaflorin really sorry, I don't understand your issue... could you tell me step by step and where the problem is present please? Thanks

In addition to everyone, I want to remember that there is the Telegram group https://t.me/common_voice_android

**Comment by rYR79435** [comment] 2020-06-24 14:51
@Sav22999 Clearing the cache has worked.. should have thought of that myself.
Was it intentional that the user has to log-in again after upgrading the app? I don't think that should have happened.

**Comment by Sav22999** [comment] 2020-06-24 14:55
@rYR79435 No, you're completely right! I'm so sorry about this incovenience 😞 .
I think it's because I've changed something in the app (basically I re-write the app from scratch).

In the future updates this issue shouldn't happen again. Sorry again

**Comment by baditaflorin** [comment] 2020-06-24 15:04
See video here for workflow https://youtu.be/oRTQqmnEFvU

Step 1. Try to login, do 2FA and get error on because I don't have account on Mozilla
Step 2. Go to Mozilla and create account. 
Step 3.go back to app and enter again user and password, even If I just did this 3 minutes ago

**Comment by baditaflorin** [comment] 2020-06-24 15:07
Maybe something along the line of the welcoming to be. Do you have an account created for voices? if not sure, you probably do not have an account, so first go and setup your account (provide link) and then come back to login

**Comment by Sav22999** [comment] 2020-06-24 15:11
@baditaflorin Ok, this is very very weird 😂
So you do the "sign up" on voice.mozilla.org, right? Then you've accepted "Privacy policy".
If you do all these things, the app should work... please, try to clear data and retry to log in. I cannot understand why it doesn't work 🤔 (Login should clear cookies automatically... it's very weird).


> Maybe something along the line of the welcoming to be. Do you have an account created for voices? if not sure, you probably do not have an account, so first go and setup your account (provide link) and then come back to login

Yeah, but actually I would like implementing the creationg of the account directly in the app (#94), but now I'm busy with the University exams, so I'll do this later... really sorry.

**Comment by baditaflorin** [comment] 2020-06-24 15:46
Good luck with you exams!

**Comment by Sav22999** [comment] 2020-06-24 16:02
@baditaflorin thanks. But please update me if that solution works.

**Closed** 2020-07-07 19:21 UTC
Labels: 🐞 bug, 📲 login, 🔶 waiting
