### ISSUE TITLE
[CRASH] Trying to edit profile infos

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Sav22999/common-voice-android#13] opened 2020-01-08 08:28 UTC
After connecting myself with my Firefox profile, Clicking on the profile button in order to modify my Common Voice account informations tend to crash the application.
If it's not that, It always crash when clicking on any profile fields, which appears as blank for me (...).

I don't know if it could be an issue fetching the account info, or the fact that I connected myself with a FireFox account.

Here's the crash log URL : https://del.dog/ackameganu

**Comment by Sav22999** [comment] 2020-01-08 10:04
Hi! First of all you cannot modify your profile information from the app (in Profile section there is a message that inform you).
Anyway, it shouldn't be in crash, so I want to solve this bug. Can you take me a screenshot of your "Profile" in website? (Of course hide your sensible data!).

**Comment by Sav22999** [comment] 2020-01-08 10:53
@PoorPocketsMcNewHold I verify and I think it's caused by no-internet-connection available. Could you try again?
(Thank you very much for your crash-log)

**Comment by Sav22999** [comment] 2020-01-09 00:04
@PoorPocketsMcNewHold in 0.0.15a release, this bug should be solved. Please, tell me

**Comment by Sav22999** [comment] 2020-01-10 13:30
Because of no-answer I close this issue. If this bug still exists, I'll reopen this issue.

**Closed by Sav22999** 2020-01-10 13:30 UTC
Labels: ✅ closed, 🐞 bug
